const COMPANY_EMAIL = 'oladapoibitoye@outlook.com';
const SENDER_EMAIL = 'oladapoibitoye@outlook.com';
const ADULT_PRICE = 80;
const CHILD_PRICE = 60;
const MAX_APPLICANTS = 21;
const json = (data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const clean=(value,max=200)=>String(value??'').replace(/[<>]/g,'').trim().slice(0,max);
function priceForAge(age){return Number(age)>=18?ADULT_PRICE:CHILD_PRICE}
function parseDateOnly(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return null;const [year,month,day]=value.split('-').map(Number),date=new Date(Date.UTC(year,month-1,day,12));if(date.getUTCFullYear()!==year||date.getUTCMonth()!==month-1||date.getUTCDate()!==day)return null;return date}
function isFutureAppointment(dateString,timeString){if(!parseDateOnly(dateString)||!/^[0-9]{2}:[0-9]{2}$/.test(timeString))return false;const [hour,minute]=timeString.split(':').map(Number),p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).reduce((a,x)=>(a[x.type]=x.value,a),{}),today=`${p.year}-${p.month}-${p.day}`;if(dateString>today)return true;if(dateString<today)return false;return hour*60+minute>Number(p.hour)*60+Number(p.minute)}
function validTimeForDate(dateString,timeString){const date=parseDateOnly(dateString);if(!date||!/^[0-9]{2}:[0-9]{2}$/.test(timeString))return false;const [hour,minute]=timeString.split(':').map(Number),total=hour*60+minute,weekend=[0,6].includes(date.getUTCDay()),start=(weekend?11:18)*60,end=(weekend?19:21)*60;return hour<=23&&minute<=59&&total>=start&&total<end&&minute%30===0}
function ageFromDob(dobString,today=new Date()){const dob=parseDateOnly(dobString);if(!dob)return null;let age=today.getUTCFullYear()-dob.getUTCFullYear();const md=today.getUTCMonth()-dob.getUTCMonth();if(md<0||(md===0&&today.getUTCDate()<dob.getUTCDate()))age--;return age}
async function clearExpiredReservations(db,appointmentDate=null){let sql=`DELETE FROM bookings WHERE status='reserved' AND expires_at IS NOT NULL AND expires_at<=datetime('now')`;const bindings=[];if(appointmentDate){sql+=' AND appointment_date=?';bindings.push(appointmentDate)}await db.prepare(sql).bind(...bindings).run()}
function ensureDatabase(context){return context.env.DB?null:json({error:'Booking database is not configured. Add a D1 binding named DB in Cloudflare.'},503)}
export async function onRequestGet(context){const missing=ensureDatabase(context);if(missing)return missing;const url=new URL(context.request.url),date=clean(url.searchParams.get('date'),10);if(!date||!parseDateOnly(date))return json({error:'A valid date is required.'},400);try{await clearExpiredReservations(context.env.DB,date);const {results}=await context.env.DB.prepare(`SELECT appointment_time FROM bookings WHERE appointment_date=? AND status IN ('reserved','confirmed') ORDER BY appointment_time`).bind(date).all();return json({ok:true,date,bookedTimes:(results||[]).map(r=>r.appointment_time)})}catch(error){console.error('Availability lookup failed',error);return json({error:'Availability could not be loaded.'},500)}}
async function sendBrevoEmail(apiKey,to,subject,html,replyTo){const response=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'accept':'application/json','content-type':'application/json','api-key':apiKey},body:JSON.stringify({sender:{name:'NIN Swindon',email:SENDER_EMAIL},to:[{email:to}],subject,htmlContent:html,replyTo:{email:replyTo||SENDER_EMAIL}})});let data=null;try{data=await response.json()}catch{}if(!response.ok)throw new Error(`Brevo ${response.status}: ${JSON.stringify(data)}`);return data}
export async function onRequestPost(context){const missing=ensureDatabase(context);if(missing)return missing;let bookingId=null;try{const contentType=context.request.headers.get('content-type')||'';if(!contentType.includes('application/json'))return json({error:'Invalid request format.'},415);const origin=context.request.headers.get('origin');if(origin){try{if(new URL(origin).origin!==new URL(context.request.url).origin)return json({error:'Invalid request origin.'},403)}catch{return json({error:'Invalid request origin.'},403)}}const body=await context.request.json();if(clean(body?.website,100))return json({error:'Unable to submit this booking.'},400);const appointmentDate=clean(body?.appointmentDate,10),appointmentTime=clean(body?.appointmentTime,5),lead=body?.lead||{},extrasInput=Array.isArray(body?.additionalApplicants)?body.additionalApplicants:[];if(!appointmentDate||!appointmentTime||!lead.name||!lead.dob||!lead.email)return json({error:'Missing required booking details.'},400);if(!validTimeForDate(appointmentDate,appointmentTime))return json({error:'Selected appointment time is outside the available booking hours.'},400);if(!isFutureAppointment(appointmentDate,appointmentTime))return json({error:'Please choose a future appointment time.'},400);if(!/^\S+@\S+\.\S+$/.test(String(lead.email))||String(lead.email).length>254)return json({error:'Please enter a valid email address.'},400);if(extrasInput.length>MAX_APPLICANTS-1)return json({error:`A booking can contain at most ${MAX_APPLICANTS} applicants.`},400);const leadAge=ageFromDob(clean(lead.dob,10));if(leadAge===null||leadAge<0||leadAge>120)return json({error:'Please enter a valid lead applicant date of birth.'},400);const extras=[];for(const person of extrasInput){const name=clean(person?.name,100),age=Number(person?.age);if(!name||!Number.isInteger(age)||age<0||age>120)return json({error:'One or more additional applicants has invalid details.'},400);extras.push({name,age})}const applicants=[{name:clean(lead.name,100),age:leadAge,lead:true},...extras.map(p=>({...p,lead:false}))],total=applicants.reduce((sum,p)=>sum+priceForAge(p.age),0);await clearExpiredReservations(context.env.DB,appointmentDate);try{const reserve=await context.env.DB.prepare(`INSERT INTO bookings(appointment_date,appointment_time,lead_name,lead_dob,lead_email,applicants_json,applicant_count,total_pence,status,expires_at) VALUES(?,?,?,?,?,?,?,?, 'confirmed',NULL)`).bind(appointmentDate,appointmentTime,clean(lead.name,100),clean(lead.dob,10),clean(lead.email,254),JSON.stringify(applicants),applicants.length,total*100).run();bookingId=reserve.meta?.last_row_id}catch(error){if(String(error?.message||error).toLowerCase().includes('unique')||String(error?.message||error).toLowerCase().includes('constraint'))return json({error:'That appointment has just been booked. Please choose another time.',code:'SLOT_TAKEN'},409);throw error}
const applicantLines=applicants.map((p,i)=>`${i+1}. ${p.name}${p.lead?' (Lead)':''} — age ${p.age} — ${p.age>=18?'Adult':'Child'} — £${priceForAge(p.age)}`).join('<br>');
const safeName=clean(lead.name,100),safeEmail=clean(lead.email,254),subject=`NIN Swindon booking confirmed — ${appointmentDate} at ${appointmentTime}`;
const companyHtml=`<h2>New NIN Swindon booking</h2><p><strong>Booking reference:</strong> ${bookingId}</p><p><strong>Date:</strong> ${appointmentDate}<br><strong>Time:</strong> ${appointmentTime}<br><strong>Lead applicant:</strong> ${safeName}<br><strong>Customer email:</strong> ${safeEmail}<br><strong>Applicants:</strong> ${applicants.length}<br><strong>Total:</strong> £${total}</p><p>${applicantLines}</p><p>Phone: 07727 695658<br>Address: 4 Kipling Gardens, Swindon</p>`;
const customerHtml=`<h2>Your NIN Swindon appointment is confirmed</h2><p>Thank you, ${safeName}. Your appointment has been booked successfully.</p><p><strong>Booking reference:</strong> ${bookingId}<br><strong>Date:</strong> ${appointmentDate}<br><strong>Time:</strong> ${appointmentTime}<br><strong>Applicants:</strong> ${applicants.length}<br><strong>Total:</strong> £${total}</p><p>${applicantLines}</p><p><strong>NIN Swindon</strong><br>4 Kipling Gardens, Swindon<br>07727 695658</p><p>Please keep this email for your records.</p>`;
const apiKey=context.env.BREVO_API_KEY;
if(!apiKey){console.error('BREVO_API_KEY is missing');return json({ok:true,bookingId,total,applicants:applicants.length,emailSent:false,message:'Your appointment has been booked successfully. Email confirmation is temporarily unavailable. Please keep your booking details and contact NIN Swindon on 07727 695658 if needed.'})}
let companySent=false,customerSent=false;try{await sendBrevoEmail(apiKey,COMPANY_EMAIL,subject,companyHtml,safeEmail);companySent=true}catch(error){console.error('Company email failed',error)}try{await sendBrevoEmail(apiKey,safeEmail,subject,customerHtml,COMPANY_EMAIL);customerSent=true}catch(error){console.error('Customer email failed',error)}
return json({ok:true,bookingId,total,applicants:applicants.length,emailSent:companySent&&customerSent,companyEmailSent:companySent,customerEmailSent:customerSent,message:companySent&&customerSent?'Your booking has been confirmed. Confirmation emails have been sent.':'Your booking has been confirmed, but one or more confirmation emails could not be delivered. Please keep your booking reference and contact NIN Swindon on 07727 695658 if needed.'})}catch(error){console.error('Booking function error',error);return json({error:'Something went wrong while creating the booking.'},500)}}
